name: Deploy GitHub Pages without Submodules

on:
  push:
    branches:
      - main  # Replace with your Pages branch (e.g., 'gh-pages')

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository without submodules
        uses: actions/checkout@v4
        with:
          submodules: false  # Disable submodule fetching
          fetch-depth: 1     # Shallow clone to minimize Git operations

      - name: Remove submodule references (workaround)
        run: |
          git config --local --unset-all submodule.DeepCaption-Ai.url || true
          rm -rf DeepCaption-Ai  # Remove any local submodule folder if present

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4