on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false  # Disable submodule fetching

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1  # If using Jekyll; adjust if not
        with:
          source: ./  # Default source directory
          destination: ./_site  # Default output directory

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4